@startuml
skinparam componentStyle rectangle
'skinparam lineType polyline

(ESTERNO) -left-> [Arrivo paziente] : \t\t\t\t\t\t
[Arrivo paziente] -up--> (CODA ACCETTAZIONE)
(CODA ACCETTAZIONE) -up-> [Accettazione]
[Accettazione] -up-> (CODA VISITA)
(CODA VISITA) -right-> [VISITA MEDICA]
[VISITA MEDICA] -down-> (ESTERNO) : Dimissione\npaziente
[VISITA MEDICA] -right-> (CODA RICOVERO) : Ricovero paziente
(CODA RICOVERO) ---> [RICOVERO DH] : Ricovero DH
(CODA RICOVERO) ---> [RICOVERO DS] : Ricovero DS
(CODA RICOVERO) ---> [RICOVERO DO] : Ricovero DO
[RICOVERO DO] -right-> [ATTESA]
[ATTESA] -left-> [RICOVERO DO]
[RICOVERO DH] ---> [ESTERNO] : Dimissione\npaziente
[RICOVERO DS] ---> [ESTERNO] : Dimissione\npaziente
[RICOVERO DO] ---> [ESTERNO] : Dimissione\npaziente
[RICOVERO DH] -[hidden]right- [RICOVERO DO]
@enduml