@startuml
skinparam componentStyle rectangle
'skinparam lineType polyline

(ESTERNO) -left-> [ARRIVO PAZIENTE]
[ARRIVO PAZIENTE] -right-> (CODA RICOVERO) : Ricovero
(CODA RICOVERO) -down-> [RICOVERO DH]
(CODA RICOVERO) -down-> [RICOVERO DS]
(CODA RICOVERO) -down-> [RICOVERO DO]
[RICOVERO DS] -down----> [ATTESA DI CURE] : Convalescenza
[RICOVERO DH] -down----> [ATTESA DI CURE] : Convalescenza
[RICOVERO DO] -down----> [ATTESA DI CURE] : Convalescenza
[RICOVERO DH] -down----> [ESTERNO] : Dimissione
[RICOVERO DS] -down----> [ESTERNO] : Dimissione
[RICOVERO DO] -down----> [ESTERNO] : Dimissione
[ATTESA DI CURE] -up-> [CODA RICOVERO] : Ricovero ripetuto
@enduml